version: '3.8'
services:
  web:
    depends_on:
      - postgres_db
    ports:
      - 8007:80
    env_file:
      - ./web/.env
    

    build: 
      context: ./web/
      dockerfile: Dockerfile
    volumes: 
      - ./web/:/app/

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes: 
      - ./api:/app


  postgres_db:
    image: postgres 
    restart : always
    platform : linux/amd64
    env_file:
      - web/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
